version: "3.3"
services:
    backend:
        container_name: backend
        image: ghcr.io/harvestcore/matroos-backend:latest
        restart: always
        ports:
            - "7000:80"
        environment:
            - WORKERS=http://worker1/;http://worker2/

    worker1:
        container_name: worker1
        image: ghcr.io/harvestcore/matroos-worker:latest
        restart: always
        ports:
            - "7001:80"

    worker2:
        container_name: worker2
        image: ghcr.io/harvestcore/matroos-worker:latest
        restart: always
        ports:
            - "7002:80"
